CREATE OR REPLACE TABLE SLS_DATA2 (
    ID NUMBER,
    F_NAME VARCHAR,
    M_NAME VARCHAR,
    L_NAME VARCHAR,
    PRICE NUMBER,
    DISCOUNT NUMBER,
    CURRENT_REVENUE NUMBER,
    PREVIOUS_REVENUE NUMBER,
    CATEGORY VARCHAR(100)
