name: Snowflake Deployment

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:

  deploy:

    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      TARGET_DATABASE: ${{ secrets.TARGET_DATABASE }}

    steps:

      #######################################################
      # Checkout Repository
      #######################################################

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      #######################################################
      # Set Target Database
      #######################################################

      - name: Set Target Database
        run: |

          echo "Current Branch : ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "dev" ]; then
            echo "TARGET_DATABASE=FIRST_TECH_DCU_D" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "TARGET_DATABASE=FIRST_TECH_DCU_U" >> $GITHUB_ENV
          else
            echo "TARGET_DATABASE=FIRST_TECH_DCU_D" >> $GITHUB_ENV
            echo "feature branch."
            #exit 1
          fi
          echo "Target Database : $TARGET_DATABASE"

      #######################################################
      # Setup Python
      #######################################################

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #######################################################
      # Install Dependencies
      #######################################################

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      #######################################################
      # Verify Git Information
      #######################################################

      - name: Display Git Information
        run: |

          echo "Repository : $GITHUB_REPOSITORY"
          echo "Workflow   : $GITHUB_WORKFLOW"
          echo "Run ID     : $GITHUB_RUN_ID"
          echo "Actor      : $GITHUB_ACTOR"
          echo "Commit     : $GITHUB_SHA"
          echo "Branch     : $GITHUB_REF_NAME"

          echo ""
          echo "Available Tags"

          git fetch --tags

          git tag --sort=-version:refname

      #######################################################
      # Execute Deployment for DEV/Other branch
      ######################################################## 

      - name: Execute Deployment for dev/other branch
        if: github.ref_name != 'main'
        run: |
          python deploy.py

      #######################################################
      # Create Git Tag
      #######################################################

      - name: Create Release Tag
        if: success() && github.ref_name == 'main'

        run: |

          git fetch --tags

          LAST_TAG=$(git tag --sort=-version:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then

              NEW_TAG="v1.0"

          else

              VERSION=${LAST_TAG#v}

              MAJOR=$(echo $VERSION | cut -d. -f1)
              MINOR=$(echo $VERSION | cut -d. -f2)

              if [ -z "$MINOR" ]; then
                  MINOR=0
              fi

              MINOR=$((MINOR + 1))

              NEW_TAG="v${MAJOR}.${MINOR}"

          fi

          echo "Creating Tag $NEW_TAG"

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
          echo "Tag $NEW_TAG created successfully."

      #######################################################
      # Execute Deployment
      #######################################################

      - name: Execute Deployment for main Branch
        if: github.ref_name == 'main' 
        run: |
          python deploy.py
